### ISSUE TITLE
MVP & Schema

### ISSUE THREAD

**Issue by BCrawfordScott** [JGYaniv/ArtAsk#1]
# MVP
- Suggestion: Remove "Step"  These MVPs don't acutally need to be done in this order (though they can be).  This is simply the list of features that, combined, make a 'minimum viable product'.
- Artists as a user type should be added to the User Auth feature.
- Artist profile pages should be a feature along with Client profile pages.
- Artists and clients profiles should be the first feature you do after Auth. That way, you'll have all your users and their types created and the following features will be simply tying the two together.
- Change "Review Form" to "User review".  Both Artists and Clients will be reviewable, so reviews will be a joins table between Clients and Artists (users to other users).  When a task is completed, both the artist and the client will be prompted to fill out a review for one another.
- The "My Tasks" page should be part of the "Tasks" feature.

# Schema
- Portfolio URL should be allowed to be null as users can be either an artist or a client (and clients likely won't have portfolios). Also - make sure that the portfolio link you provide for your seed data actually goes somewhere (maybe your github or personal site????)
- Remove `profile_picture_url` as you'll be using active storage to hold photos.  We have a tutorial that takes you through how to set it up.
- An advanced concern to consider is why make the email unique?  What if I want to be both a client and an artist?  Just a thought...
- With your current layout, artists can only do one type of task, and tasks may only have one type.  This is fine to start, but consider making the types table a polymorphic table with a `typable_type` and a `typable_id`.  That way both the artists and the tasks would use this table to record types and they could both have many types based on the type name.
- Reviews: it seems that right now only tasks are reviewed.  Should tasks be reviews or the artist/client?  Either way is fine.

Great work!

**Comment by JGYaniv** [comment]
I believe all these notes have been addressed!
