### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by PLUCS2** [JGYaniv/ArtAsk#2]
- [x] What is task type? How is it associated with a user?

**Comment by JGYaniv** [comment]
Task types are categories, ie Music, Poster, DJ, Curate. A client-type user will select one of these task types when forming a new task. An artist-type user will select which types of tasks they can provide, which will be associated through the task-type-artists joins tables.

When a client user is creating a task, selecting a task-type will filter which artists appear as options (based on the task-type-artists joins table).

My plan was to poll the database using the task-type artists association, to return a list of all artists who are interested in helping out with those types of tasks. Do you think this should also be reflected somehow in the state?

**Comment by PLUCS2** [comment]
Ah, lets talk about this in our 1 on 1.

**Comment by JGYaniv** [comment]
Updated state as per our conversation, now includes Tasks and Reviews in entities. Normalized Users entity by removing nested reviews and replacing with an array of ids.
